version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks: [backend]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [backend]

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks: [backend]

  identity:
    build:
      context: .
      dockerfile: src/Services/IdentityService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [postgres]
    ports:
      - "5001:8080"
    networks: [backend]

  catalog:
    build:
      context: .
      dockerfile: src/Services/CatalogService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [postgres, redis]
    ports:
      - "5002:8080"
    networks: [backend]

  order:
    build:
      context: .
      dockerfile: src/Services/OrderService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [postgres, rabbitmq]
    ports:
      - "5003:8080"
    networks: [backend]

  payment:
    build:
      context: .
      dockerfile: src/Services/PaymentService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [rabbitmq]
    ports:
      - "5004:8080"
    networks: [backend]

  monolith:
    build:
      context: .
      dockerfile: src/Monolith/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: [postgres, redis]
    ports:
      - "5000:8080"
    networks: [backend]

  webapp:
    build:
      context: ./src/WebApp
      dockerfile: Dockerfile
    depends_on: [identity, catalog, order, payment]
    ports:
      - "5173:80"
    networks: [backend]

volumes:
  pgdata:

networks:
  backend:
    driver: bridge


